name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: wilab/pnpm-monorepo:v0.0.4
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      
