name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: wilab/pnpm-monorepo:v0.0.4
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
